export {
	type DestinationAutocompleteRequest,
	DestinationAutocompleteRequestSchema,
	type DestinationAutocompleteResult,
	DestinationAutocompleteResultSchema,
	type DestinationPrediction,
	DestinationPredictionSchema,
	type DestinationSelectionRequest,
	DestinationSelectionRequestSchema,
	type DestinationSelectionResult,
	DestinationSelectionResultSchema,
	type DestinationUnavailableReason,
	type PrivateDestination,
	PrivateDestinationSchema,
} from "./schema";
